export default {
  TRIGGER_MESSAGES: [
    'happy birthday',
    'birthday',
    'happy birth',
    'happy day of',
    'hbd',
    'happybday',
    'bday',
    'hbday',
    'birth',
    'sto lat',
    'stolat',
  ],
  CHANNEL_NAME: 'hicelina',
  FONTS: [
    'Anton',
    'IndieFlower',
    'Josefin Sans',
    'Lobster',
    'Lora',
    'Luckiest Guy',
    'Oswald',
    'Roboto Slab',
    'Rubik',
    'Special Elite',
  ],
  OPACITY: 1,
  SCREEN_HEIGHT: 720,
  SCREEN_WIDTH: 1280,
  TEXTBOX_HEIGHT: 400,
  TEXTBOX_TIMER: 7 * 1000,
  TEXTBOX_WIDTH: 600,
};
