export default {
  TRIGGER_MESSAGES: ['happy birthday', 'birthday', 'happy birth', 'happy day of', 'hbd'],
  CHANNEL_NAME: 'hicelina',
  FONTS: [
    'Anton',
    'IndieFlower',
    'Josefin Sans',
    'Lobster',
    'Lora',
    'Luckiest Guy',
    'Oswald',
    'Roboto Slab',
    'Rubik',
    'Special Elite',
  ],
  OPACITY: 1,
  SCREEN_HEIGHT: 1440,
  SCREEN_WIDTH: 2560,
  TEXTBOX_HEIGHT: 600,
  TEXTBOX_TIMER: 7 * 1000,
  TEXTBOX_WIDTH: 1000,
};
